// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using NomHadopi.Models.EF;
using System;

namespace NomHadopi.Migrations
{
    [DbContext(typeof(NameSuggestDbContext))]
    partial class NameSuggestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("NomHadopi.Models.EF.Suggestion", b =>
                {
                    b.Property<int>("SuggestionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorEmail");

                    b.Property<string>("AuthorName");

                    b.Property<DateTime>("DateSuggested");

                    b.Property<string>("SuggestionValue");

                    b.Property<string>("UserIP");

                    b.HasKey("SuggestionID");

                    b.HasIndex("UserIP");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("NomHadopi.Models.EF.UpVote", b =>
                {
                    b.Property<int>("UpVoteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IpUser");

                    b.Property<int>("SuggestionId");

                    b.HasKey("UpVoteID");

                    b.HasIndex("SuggestionId");

                    b.ToTable("UpVotes");
                });

            modelBuilder.Entity("NomHadopi.Models.EF.UpVote", b =>
                {
                    b.HasOne("NomHadopi.Models.EF.Suggestion", "Suggestion")
                        .WithMany("UpVotes")
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
